version: '3.5'

networks:
  twitter-network:
    external: false
    name: twitter-network

services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker

    volumes:
      - ./:/var/www

    networks:
      - twitter-network

    ports:
      - '10080:80'

    links:
      - app

  app:
    build:
      context: ./
      dockerfile: .docker/app.docker

    volumes:
      - ./:/var/www

    networks:
      - twitter-network

    links:
      - database


    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    networks:
      - twitter-network

    ports:
      - '33020:3306'

    environment:
      - 'MYSQL_ROOT_PASSWORD=aDuaCAL4rUE5yMeVlAb9uMUjxw13pdNJ'
      - 'MYSQL_DATABASE=app'

  database-ui:
    image: phpmyadmin/phpmyadmin

    networks:
      - twitter-network

    ports:
      - '10081:80'

    links:
      - database

    environment:
      - 'PMA_HOST=database'
